### PR TITLE
Remove education ab test

### PR DESCRIPTION
**Pull request by steventux**
https://trello.com/c/HTNxCxSJ/66-remove-education-ab-test-in-manuals-frontend

Removes the education navigation AB test and B variant.

### CODE REVIEW

**Comment by vanitabarrett** [comment]
Can we remove `config.navigation_ab_test_dimension = 41` in `config/application.rb`?

**Comment by steventux** [comment]
@vanitabarrett :+1: updated

**Comment by fofr** [comment]
Are the stubbed education manuals still needed?
https://github.com/alphagov/manuals-frontend/blame/remove-education-ab-test/spec/support/manual_helpers.rb#L19

**Comment by steventux** [comment]
@fofr good spot - removed/rebased

**Comment by fofr** [comment]
Think we could also remove:
* taxonomy_beta_label.html.erb
* taxonomy_sidebar.html.erb
* taxonomy methods on manuals presenter
* further references to nav_helper in manuals and documents presenter

**Pull request merged**
