### PR TITLE
Update Rails version to 4.1.0

### PR DESCRIPTION
**Pull request by jackscotti**
I tried to update to 4.2.0 but:
- Slimmer (5.0.0 or 7.0.0) requires nokogiri (1.5.11)
- Rails (4.2.0) requires nokogiri (~> 1.6.0)

If we really want to update to Rails 4.2.0 we will need to update Nokogiri in Slimmer too.

For the moment, we can proceed with updating Rails to 4.1.0.

https://www.pivotaltracker.com/story/show/88885714

### CODE REVIEW

**Comment by jamiecobbett** [comment]
Actually, Slimmer 7.0.0 relaxes the dependency to >1.5.0 and < 1.7.0 https://github.com/alphagov/slimmer/blob/master/CHANGELOG.md, so it should be possible to get to Rails 4.2.0.

**Comment by jackscotti** [comment]
That's the error I get:

```Bundler could not find compatible versions for gem "nokogiri":

  In Gemfile:
    rails (= 4.2.0) ruby depends on
      actionpack (= 4.2.0) ruby depends on
        rails-dom-testing (>= 1.0.5, ~> 1.0) ruby depends on
          nokogiri (~> 1.6.0) ruby

    slimmer (~> 7.0.0) ruby depends on
      nokogiri (1.5.11)

```

**Comment by jamiecobbett** [comment]
Have you tried: `bundle update rails slimmer`?

**Comment by jackscotti** [comment]
I created a new branch https://github.com/alphagov/manuals-frontend/pull/131 , thanks @jamiecobbett for pointing out!

**Pull request closed without merging**
