### PR TITLE
Remove govuk_frontend_toolkit dependency

### PR DESCRIPTION
**Pull request by kr8n3r**
Removes the dependency

### CODE REVIEW

**Comment by andysellick** [comment]
Is primary links used by any other apps? Would it be better in the gem?

**Comment by kr8n3r** [comment]
it's currently used by these active repos
https://github.com/alphagov/manuals-publisher

**Comment by sihugh** [comment]
@kr8n3r this needs a rebase now because of Gemfile bumps :-(

**Comment by kr8n3r** [comment]
migration upstream https://github.com/alphagov/govuk_publishing_components/pull/1201

**Comment by kr8n3r** [comment]
is this ready to go now?

**Pull request merged**
